import { type NextPage } from "next";
import Head from "next/head";
import { siteConfig } from "~/config/site";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>{siteConfig.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="container grid items-center gap-6 pb-8 pt-6 md:py-10">
        <div className="flex max-w-[980px] flex-col items-start gap-2">
          <h1 className="text-3xl font-extrabold leading-tight tracking-tighter md:text-4xl">
            A beautiful online to-do list app
          </h1>
          <p className="max-w-[700px] text-lg text-muted-foreground">
            Make it easier for you to plan your day by using to-do lists.
          </p>
        </div>
      </section>
    </>
  );
};

export default Home;
